// Migrated by hand

// pub const MIR_alloc_t = ?*opaque {};
// pub const MIR_code_alloc_t = ?*opaque {};
// pub const MIR_context_t = ?*opaque {};
// pub const MIR_module_t = *opaque {};
// pub const MIR_item_t = *opaque {};
// const MIR_val_t = opaque {};
// pub const MIR_type_t = c_uint;
// const struct_MIR_var = extern struct {
//     type: MIR_type_t = @import("std").mem.zeroes(MIR_type_t),
//     name: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
//     size: usize = @import("std").mem.zeroes(usize),
// };
// pub const MIR_var_t = struct_MIR_var;
// const MIR_func_t = *opaque {};
// const MIR_reg_t = u32;
// const MIR_insn_t = *opaque {};
// const MIR_label_t = *opaque {};
// const MIR_op_t = opaque {};
// const MIR_disp_t = i64;
// const MIR_scale_t = u8;
// const MIR_alias_t = u32;
// const MIR_insn_code_t = c_uint;

// extern fn _MIR_get_api_version() f64;
// extern fn _MIR_init(MIR_alloc_t, MIR_code_alloc_t) MIR_context_t;
// extern fn MIR_finish(ctx: MIR_context_t) void;
// extern fn MIR_load_module(MIR_context_t, MIR_module_t) void;
// extern fn MIR_load_external(MIR_context_t, [*c]const u8, *void) void;
// const MIR_set_interface_fn = ?*const fn (MIR_context_t, MIR_item_t) callconv(.C) void;
// const MIR_import_resolver_fn = ?*const fn ([*c]const u8) callconv(.C) void;
// extern fn MIR_link(MIR_context_t, MIR_set_interface_fn, MIR_import_resolver_fn) void;
// extern fn MIR_interp_arr(MIR_context_t, MIR_item_t, [*c]MIR_val_t, usize, [*c]MIR_val_t) void;
// extern fn MIR_new_module(MIR_context_t, [*c]const u8) MIR_module_t;
// extern fn MIR_finish_module(MIR_context_t) void;
// extern fn MIR_new_import(MIR_context_t, [*c]const u8) MIR_item_t;
// extern fn MIR_new_export(MIR_context_t, [*c]const u8) MIR_item_t;
// extern fn MIR_new_proto_arr(MIR_context_t, [*c]const u8, usize, [*c]MIR_type_t, usize, [*c]MIR_var_t) MIR_item_t;
// extern fn MIR_new_func_arr(MIR_context_t, [*c]const u8, usize, [*c]MIR_type_t, usize, [*c]MIR_var_t) MIR_item_t;
// extern fn MIR_new_data(MIR_context_t, [*c]const u8, [*c]MIR_type_t, usize, [*c]void) MIR_item_t;
// extern fn MIR_new_func_reg(MIR_context_t, MIR_func_t, MIR_type_t, [*c]const u8) MIR_reg_t;
// extern fn MIR_reg(MIR_context_t, [*c]const u8, MIR_func_t) MIR_reg_t;
// extern fn MIR_new_label(MIR_context_t) MIR_insn_t;
// extern fn MIR_append_insn(MIR_context_t, MIR_item_t, MIR_insn_t) void;
// extern fn MIR_finish_func(MIR_context_t) void;
// extern fn MIR_new_ret_insn(MIR_context_t, usize, ...) MIR_insn_t;
// extern fn MIR_new_call_insn(MIR_context_t, usize, ...) MIR_insn_t;
// extern fn MIR_new_reg_op(MIR_context_t, MIR_reg_t) MIR_op_t;
// extern fn MIR_new_int_op(MIR_context_t, i64) MIR_op_t;
// extern fn MIR_new_uint_op(MIR_context_t, u64) MIR_op_t;
// extern fn MIR_new_ref_op(MIR_context_t, MIR_item_t) MIR_op_t;
// extern fn MIR_new_label_op(MIR_context_t, MIR_label_t) MIR_op_t;
// extern fn MIR_new_mem_op(MIR_context_t, MIR_type_t, MIR_disp_t, MIR_reg_t, MIR_reg_t, MIR_scale_t) MIR_op_t;
// extern fn MIR_new_alias_mem_op(MIR_context_t, MIR_type_t, MIR_disp_t, MIR_reg_t, MIR_reg_t, MIR_scale_t, MIR_alias_t, MIR_alias_t) MIR_op_t;
// extern fn MIR_new_insn_arr(MIR_context_t, MIR_insn_code_t, usize, *MIR_op_t) MIR_insn_t;

// Expaned from mir.h

pub const MIR_no_error: c_int = 0;
pub const MIR_syntax_error: c_int = 1;
pub const MIR_binary_io_error: c_int = 2;
pub const MIR_alloc_error: c_int = 3;
pub const MIR_finish_error: c_int = 4;
pub const MIR_no_module_error: c_int = 5;
pub const MIR_nested_module_error: c_int = 6;
pub const MIR_no_func_error: c_int = 7;
pub const MIR_func_error: c_int = 8;
pub const MIR_vararg_func_error: c_int = 9;
pub const MIR_nested_func_error: c_int = 10;
pub const MIR_wrong_param_value_error: c_int = 11;
pub const MIR_hard_reg_error: c_int = 12;
pub const MIR_reserved_name_error: c_int = 13;
pub const MIR_import_export_error: c_int = 14;
pub const MIR_undeclared_func_reg_error: c_int = 15;
pub const MIR_repeated_decl_error: c_int = 16;
pub const MIR_reg_type_error: c_int = 17;
pub const MIR_wrong_type_error: c_int = 18;
pub const MIR_unique_reg_error: c_int = 19;
pub const MIR_undeclared_op_ref_error: c_int = 20;
pub const MIR_ops_num_error: c_int = 21;
pub const MIR_call_op_error: c_int = 22;
pub const MIR_unspec_op_error: c_int = 23;
pub const MIR_wrong_lref_error: c_int = 24;
pub const MIR_ret_error: c_int = 25;
pub const MIR_op_mode_error: c_int = 26;
pub const MIR_out_op_error: c_int = 27;
pub const MIR_invalid_insn_error: c_int = 28;
pub const MIR_ctx_change_error: c_int = 29;
pub const enum_MIR_error_type = c_uint;
pub const MIR_error_type_t = enum_MIR_error_type;
pub const MIR_error_func_t = ?*const fn (MIR_error_type_t, [*c]const u8, ...) callconv(.c) noreturn;
pub const MIR_MOV: c_int = 0;
pub const MIR_FMOV: c_int = 1;
pub const MIR_DMOV: c_int = 2;
pub const MIR_LDMOV: c_int = 3;
pub const MIR_EXT8: c_int = 4;
pub const MIR_EXT16: c_int = 5;
pub const MIR_EXT32: c_int = 6;
pub const MIR_UEXT8: c_int = 7;
pub const MIR_UEXT16: c_int = 8;
pub const MIR_UEXT32: c_int = 9;
pub const MIR_I2F: c_int = 10;
pub const MIR_I2D: c_int = 11;
pub const MIR_I2LD: c_int = 12;
pub const MIR_UI2F: c_int = 13;
pub const MIR_UI2D: c_int = 14;
pub const MIR_UI2LD: c_int = 15;
pub const MIR_F2I: c_int = 16;
pub const MIR_D2I: c_int = 17;
pub const MIR_LD2I: c_int = 18;
pub const MIR_F2D: c_int = 19;
pub const MIR_F2LD: c_int = 20;
pub const MIR_D2F: c_int = 21;
pub const MIR_D2LD: c_int = 22;
pub const MIR_LD2F: c_int = 23;
pub const MIR_LD2D: c_int = 24;
pub const MIR_NEG: c_int = 25;
pub const MIR_NEGS: c_int = 26;
pub const MIR_FNEG: c_int = 27;
pub const MIR_DNEG: c_int = 28;
pub const MIR_LDNEG: c_int = 29;
pub const MIR_ADDR: c_int = 30;
pub const MIR_ADDR8: c_int = 31;
pub const MIR_ADDR16: c_int = 32;
pub const MIR_ADDR32: c_int = 33;
pub const MIR_ADD: c_int = 34;
pub const MIR_ADDS: c_int = 35;
pub const MIR_FADD: c_int = 36;
pub const MIR_DADD: c_int = 37;
pub const MIR_LDADD: c_int = 38;
pub const MIR_SUB: c_int = 39;
pub const MIR_SUBS: c_int = 40;
pub const MIR_FSUB: c_int = 41;
pub const MIR_DSUB: c_int = 42;
pub const MIR_LDSUB: c_int = 43;
pub const MIR_MUL: c_int = 44;
pub const MIR_MULS: c_int = 45;
pub const MIR_FMUL: c_int = 46;
pub const MIR_DMUL: c_int = 47;
pub const MIR_LDMUL: c_int = 48;
pub const MIR_DIV: c_int = 49;
pub const MIR_DIVS: c_int = 50;
pub const MIR_UDIV: c_int = 51;
pub const MIR_UDIVS: c_int = 52;
pub const MIR_FDIV: c_int = 53;
pub const MIR_DDIV: c_int = 54;
pub const MIR_LDDIV: c_int = 55;
pub const MIR_MOD: c_int = 56;
pub const MIR_MODS: c_int = 57;
pub const MIR_UMOD: c_int = 58;
pub const MIR_UMODS: c_int = 59;
pub const MIR_AND: c_int = 60;
pub const MIR_ANDS: c_int = 61;
pub const MIR_OR: c_int = 62;
pub const MIR_ORS: c_int = 63;
pub const MIR_XOR: c_int = 64;
pub const MIR_XORS: c_int = 65;
pub const MIR_LSH: c_int = 66;
pub const MIR_LSHS: c_int = 67;
pub const MIR_RSH: c_int = 68;
pub const MIR_RSHS: c_int = 69;
pub const MIR_URSH: c_int = 70;
pub const MIR_URSHS: c_int = 71;
pub const MIR_EQ: c_int = 72;
pub const MIR_EQS: c_int = 73;
pub const MIR_FEQ: c_int = 74;
pub const MIR_DEQ: c_int = 75;
pub const MIR_LDEQ: c_int = 76;
pub const MIR_NE: c_int = 77;
pub const MIR_NES: c_int = 78;
pub const MIR_FNE: c_int = 79;
pub const MIR_DNE: c_int = 80;
pub const MIR_LDNE: c_int = 81;
pub const MIR_LT: c_int = 82;
pub const MIR_LTS: c_int = 83;
pub const MIR_ULT: c_int = 84;
pub const MIR_ULTS: c_int = 85;
pub const MIR_FLT: c_int = 86;
pub const MIR_DLT: c_int = 87;
pub const MIR_LDLT: c_int = 88;
pub const MIR_LE: c_int = 89;
pub const MIR_LES: c_int = 90;
pub const MIR_ULE: c_int = 91;
pub const MIR_ULES: c_int = 92;
pub const MIR_FLE: c_int = 93;
pub const MIR_DLE: c_int = 94;
pub const MIR_LDLE: c_int = 95;
pub const MIR_GT: c_int = 96;
pub const MIR_GTS: c_int = 97;
pub const MIR_UGT: c_int = 98;
pub const MIR_UGTS: c_int = 99;
pub const MIR_FGT: c_int = 100;
pub const MIR_DGT: c_int = 101;
pub const MIR_LDGT: c_int = 102;
pub const MIR_GE: c_int = 103;
pub const MIR_GES: c_int = 104;
pub const MIR_UGE: c_int = 105;
pub const MIR_UGES: c_int = 106;
pub const MIR_FGE: c_int = 107;
pub const MIR_DGE: c_int = 108;
pub const MIR_LDGE: c_int = 109;
pub const MIR_ADDO: c_int = 110;
pub const MIR_ADDOS: c_int = 111;
pub const MIR_SUBO: c_int = 112;
pub const MIR_SUBOS: c_int = 113;
pub const MIR_MULO: c_int = 114;
pub const MIR_MULOS: c_int = 115;
pub const MIR_UMULO: c_int = 116;
pub const MIR_UMULOS: c_int = 117;
pub const MIR_JMP: c_int = 118;
pub const MIR_BT: c_int = 119;
pub const MIR_BTS: c_int = 120;
pub const MIR_BF: c_int = 121;
pub const MIR_BFS: c_int = 122;
pub const MIR_BEQ: c_int = 123;
pub const MIR_BEQS: c_int = 124;
pub const MIR_FBEQ: c_int = 125;
pub const MIR_DBEQ: c_int = 126;
pub const MIR_LDBEQ: c_int = 127;
pub const MIR_BNE: c_int = 128;
pub const MIR_BNES: c_int = 129;
pub const MIR_FBNE: c_int = 130;
pub const MIR_DBNE: c_int = 131;
pub const MIR_LDBNE: c_int = 132;
pub const MIR_BLT: c_int = 133;
pub const MIR_BLTS: c_int = 134;
pub const MIR_UBLT: c_int = 135;
pub const MIR_UBLTS: c_int = 136;
pub const MIR_FBLT: c_int = 137;
pub const MIR_DBLT: c_int = 138;
pub const MIR_LDBLT: c_int = 139;
pub const MIR_BLE: c_int = 140;
pub const MIR_BLES: c_int = 141;
pub const MIR_UBLE: c_int = 142;
pub const MIR_UBLES: c_int = 143;
pub const MIR_FBLE: c_int = 144;
pub const MIR_DBLE: c_int = 145;
pub const MIR_LDBLE: c_int = 146;
pub const MIR_BGT: c_int = 147;
pub const MIR_BGTS: c_int = 148;
pub const MIR_UBGT: c_int = 149;
pub const MIR_UBGTS: c_int = 150;
pub const MIR_FBGT: c_int = 151;
pub const MIR_DBGT: c_int = 152;
pub const MIR_LDBGT: c_int = 153;
pub const MIR_BGE: c_int = 154;
pub const MIR_BGES: c_int = 155;
pub const MIR_UBGE: c_int = 156;
pub const MIR_UBGES: c_int = 157;
pub const MIR_FBGE: c_int = 158;
pub const MIR_DBGE: c_int = 159;
pub const MIR_LDBGE: c_int = 160;
pub const MIR_BO: c_int = 161;
pub const MIR_UBO: c_int = 162;
pub const MIR_BNO: c_int = 163;
pub const MIR_UBNO: c_int = 164;
pub const MIR_LADDR: c_int = 165;
pub const MIR_JMPI: c_int = 166;
pub const MIR_CALL: c_int = 167;
pub const MIR_INLINE: c_int = 168;
pub const MIR_JCALL: c_int = 169;
pub const MIR_SWITCH: c_int = 170;
pub const MIR_RET: c_int = 171;
pub const MIR_JRET: c_int = 172;
pub const MIR_ALLOCA: c_int = 173;
pub const MIR_BSTART: c_int = 174;
pub const MIR_BEND: c_int = 175;
pub const MIR_VA_ARG: c_int = 176;
pub const MIR_VA_BLOCK_ARG: c_int = 177;
pub const MIR_VA_START: c_int = 178;
pub const MIR_VA_END: c_int = 179;
pub const MIR_LABEL: c_int = 180;
pub const MIR_UNSPEC: c_int = 181;
pub const MIR_PRSET: c_int = 182;
pub const MIR_PRBEQ: c_int = 183;
pub const MIR_PRBNE: c_int = 184;
pub const MIR_USE: c_int = 185;
pub const MIR_PHI: c_int = 186;
pub const MIR_INVALID_INSN: c_int = 187;
pub const MIR_INSN_BOUND: c_int = 188;
pub const MIR_insn_code_t = c_uint;

pub const MIR_T_I8: c_int = 0;
pub const MIR_T_U8: c_int = 1;
pub const MIR_T_I16: c_int = 2;
pub const MIR_T_U16: c_int = 3;
pub const MIR_T_I32: c_int = 4;
pub const MIR_T_U32: c_int = 5;
pub const MIR_T_I64: c_int = 6;
pub const MIR_T_U64: c_int = 7;
pub const MIR_T_F: c_int = 8;
pub const MIR_T_D: c_int = 9;
pub const MIR_T_LD: c_int = 10;
pub const MIR_T_P: c_int = 11;
pub const MIR_T_BLK: c_int = 12;
pub const MIR_T_RBLK: c_int = 17;
pub const MIR_T_UNDEF: c_int = 18;
pub const MIR_T_BOUND: c_int = 19;
