# This script is more or less just doing
#   python -m dis the_file.py
# but turning the output into a zig source file for easy consumption

from dis import get_instructions
from pathlib import Path
from collections import namedtuple
import subprocess

from sys import argv

# Instruction(opname='RESUME', opcode=151, arg=0, argval=0, argrepr='', offset=0, starts_line=0, is_jump_target=False, positions=Positions(lineno=0, end_lineno=1, col_offset=0, end_col_offset=0)

Example = namedtuple("Example", "name path")

print("""// This file is generated by the build process
// Do not manually edit, as edits will be clobbered by the build

const OpCode = @import("../bytecode/opcodes.zig").OpCode;
const StaticStringMap = @import("std").StaticStringMap;
const object = @import("../object.zig");

pub const Instruction = struct {
  opcode: OpCode,
  arg: ?u8,
  argval: object.Object,
  argrepr: ?[]const u8 = null,
  offset: u16,
  starts_line: ?u16,
  is_jump_target: bool,
  // TODO: positions
};

const InstructionSet = []const Instruction;

pub const Example = struct {
  path: [] const u8,
  source: [] const u8,
  return_code: u8,
  captured_stdout: [] const u8,
  captured_stderr: [] const u8,
  instructions: InstructionSet,
};

fn opnameToEnum(opcode: u8, opcode_str: []const u8, opname: OpCode) OpCode {
  const int_op: OpCode = @enumFromInt(opcode);
  if(int_op != opname) @compileError(@tagName(opname) ++ " must have value " ++ opcode_str);
  return opname;
}

""")

examples = []

def as_hex_string(s: str) -> str:
    byte_array = s.encode('utf-8')  # get bytes
    hex_values = [f"0x{b:02x}" for b in byte_array]  # format each byte
    return ", ".join(hex_values)
def argval_to_PyArgVal(val):
    if val is None:
        return "object.None"
    elif isinstance(val, str):
        return 'object.Object{ .string = .{ .string = &[_]u8{' + as_hex_string(val) + '} } }'
    elif isinstance(val, int):
        return 'object.Object{ .int = ' + str(val) + ' }'
    elif isinstance(val, float):
        return 'object.Object{ .float = ' + str(val) + ' }'
    else:
        # this is wrong, for example sometimes it can be a symbol
        # like a method name
        return 'object.None'


def instruction_to_zig(insn):
    return f"""  .{{
      //.opname = "{insn.opname}",
      .opcode = opnameToEnum({insn.opcode}, "{insn.opcode}", .@"{insn.opname.lower()}"),
      .arg = {"null" if insn.arg is None else insn.arg},
      // TODO: escape double quotes
      .argval = {argval_to_PyArgVal(insn.argval)},
      //.argrepr = "{insn.argrepr}",
      .offset = {insn.offset},
      .starts_line = {"null" if insn.starts_line is None else insn.starts_line},
      .is_jump_target = {"true" if insn.is_jump_target else "false"},
  }},"""
def instructions_to_zig(example_path, instruction_generator):
    x = Path(example_path)
    example_name = "_".join([x.parent.stem, x.stem])

    examples.append(Example(example_name, example_path))
    print(f"pub const {example_name} = [_]Instruction {{")
    for instruction in instruction_generator:
        print(instruction_to_zig(instruction))
    print("};")

# def bytes_to_zig_string(bytes):
#     hex = bytes.hex()
#     zig_hex = ",".join(["0x" + hex[i:i+2] for i in range(0, len(hex), 2)])
#     return "".join(["[_]u8 {", zig_hex, "}"])

for example_path in argv[1:]:
    with open(example_path) as example_file:
        example = example_file.read()
        instructions_to_zig(example_path, get_instructions(example))

print("""
const KV = struct { []const u8, Example };
pub const examples = StaticStringMap(Example).initComptime([_]KV{
""")
for example in examples:
    # We run the script in a subprocess and capture its stdout, stderr, and status
    cmd_result = subprocess.run(["python", example.path], capture_output=True)
    # clip out quotes and final newline
    stdout_result = repr(cmd_result.stdout.decode())[1:-3]
	# TODO!!!! figure out how to print a valid zig string from python bytes
    # stderr_result = repr(cmd_result.stderr.decode())[1:-1]
    # stderr_result.encode("unicode_escape")

    print(f"""
    .{{ "{example.name}", .{{
    	.path = "{example.path}",
    	.return_code = {cmd_result.returncode},
    	.captured_stdout = "{stdout_result}",
    	.captured_stderr = "",
    	.source = @embedFile("{example.path}"),
    	.instructions = &{example.name} }}
    }},
    """)
print("});")
