from dis import get_instructions
from pathlib import Path
from os.path import relpath
from collections import namedtuple

from sys import argv

# Instruction(opname='RESUME', opcode=151, arg=0, argval=0, argrepr='', offset=0, starts_line=0, is_jump_target=False, positions=Positions(lineno=0, end_lineno=1, col_offset=0, end_col_offset=0)

Example = namedtuple("Example", "name path")

print("""// This file is generated by the build process
// Do not manually edit, as edits will be clobbered by the build

const ComptimeStringMap = @import("std").ComptimeStringMap;

pub const Instruction = struct {
  opname: []const u8,
  opcode: u8,
  arg: ?u8,
  argval: ?u8 = null,
  argrepr: ?[]const u8 = null,
  offset: u16,
  starts_line: ?u16,
  is_jump_target: bool,
  // TODO: positions
};

const InstructionSet = []const Instruction;

const Example = struct {
  path: [] const u8,
  source: [] const u8,
  instructions: InstructionSet,
};

""")

examples = []

def instruction_to_zig(insn):
    return f"""  .{{
      .opname = "{insn.opname}",
      .opcode = {insn.opcode},
      .arg = {"null" if insn.arg is None else insn.arg},
      // TODO: escape double quotes
      //.argval = {"null" if insn.argval is None else '"' + str(insn.argval) + '"'},
      //.argrepr = "{insn.argrepr}",
      .offset = {insn.offset},
      .starts_line = {"null" if insn.starts_line is None else insn.starts_line},
      .is_jump_target = {"true" if insn.is_jump_target else "false"},
  }},"""
def instructions_to_zig(example_path, instruction_generator):
    example_name = Path(example_path).stem

    examples.append(Example(example_name, relpath(example_path, "src/test")))
    print(f"pub const {example_name} = [_]Instruction {{")
    for instruction in instruction_generator:
        print(instruction_to_zig(instruction))
    print("};")

for example_path in argv[1:]:
    with open(example_path) as example_file:
        example = example_file.read()
        instructions_to_zig(example_path, get_instructions(example))

print("""
const KV = struct { []const u8, Example };
pub const examples = ComptimeStringMap(Example, [_]KV{
""")
for example in examples:
    print(f'  .{{ "{example.name}", .{{ .path = "{example.path}", .source = @embedFile("{example.path}"), .instructions = &{example.name} }} }},')
print("});")
