const std = @import("std");
const cfg = @import("bytecode/cfg.zig");
const TaggedValue = @import("TaggedValue.zig");
const lower = @import("ir/lower.zig");
pub const lowerCodeObject = lower.lowerCodeObject;
const assert = std.debug.assert;
const testing = std.testing;

pub const OpCode = enum(u8) {
    nop,
    identity,
    branch,
    jump,
    ret,
    phi,
    upsilon,

    arg,

    const_obj,

    py_truthy,
    py_binary_op,
    py_call,

    pub inline fn isTerminator(op: OpCode) bool {
        return effectsOf(op).terminator;
    }
};

const Effects = packed struct(u8) {
    reads_world: bool = false,
    writes_world: bool = false,
    can_raise: bool = false,
    can_exit: bool = false,
    can_allocate: bool = false,
    terminator: bool = false,
    has_result: bool = false,
    _padding: i1 = 0,
};

fn effectsOf(op: OpCode) Effects {
    return switch (op) {
        .nop, .identity, .phi, .upsilon => .{},
        .branch, .jump, .ret => .{ .terminator = true },
        .arg => .{},
        .const_obj => .{},
        .py_truthy => .{},
        .py_binary_op => .{ .reads_world = true, .writes_world = true, .can_raise = true, .can_allocate = true, .has_result = true },
        .py_call => .{ .reads_world = true, .writes_world = true, .can_raise = true, .can_allocate = true, .has_result = true },
    };
}

const Repr = enum(u8) {
    none,
    i1,
    i32,
    i64,
    f64,
    ptr, // raw pointer
    object, // owned *Object reference
    tagged, // high bit tagged immediate value or *Object

    fn needsBoxing(r: Repr) bool {
        return switch (r) {
            .i1, .i32, .i64, .f64 => true,
            .none, .ptr, .object, .tagged => false,
        };
    }
};

pub const ValueId = enum(u32) {
    none = std.math.maxInt(u32),
    _,

    pub inline fn idx(b: ValueId) u32 {
        assert(b != .none);
        return @intFromEnum(b);
    }
    pub inline fn from(i: u32) ValueId {
        return @enumFromInt(i);
    }
};

pub const BlockId = enum(u32) {
    none = std.math.maxInt(u32),
    _,

    pub inline fn idx(b: BlockId) u32 {
        assert(b != .none);
        return @intFromEnum(b);
    }
    pub inline fn from(i: u32) BlockId {
        return @enumFromInt(i);
    }
};

pub const LocalIdx = u16;

pub const Value = struct {
    op: OpCode,
    repr: Repr,
    origin: u32 = 0, //TODO: fix me, no default value
    lhs: u32,
    rhs: u32,

    pub fn fromTagged(value: TaggedValue) Value {
        return .{
            .op = .const_obj,
            .repr = .tagged,
            .lhs = value.highWord(),
            .rhs = value.lowWord(),
        };
    }

    pub fn asTagged(value: Value) TaggedValue {
        return TaggedValue.assemble(value.lhs, value.rhs);
    }

    const True = Value{
        .op = .py_truthy,
        .repr = .i1,
        .lhs = 1,
        .rhs = 0,
    };

    const None: Value = .fromTagged(.None);
};

const BranchPayload = struct {
    const Extra = struct {
        then: BlockId,
        @"else": BlockId,
    };

    predicate: u32,
    extra: Extra,
};

const Block = struct {
    // TODO: would a span into the procedure's values would be better?
    values: std.ArrayList(ValueId) = .empty,
    preds: std.ArrayList(BlockId) = .empty,
    sealed: bool = false,

    fn deinit(b: *Block, allocator: std.mem.Allocator) void {
        b.preds.deinit(allocator);
        b.values.deinit(allocator);
    }

    /// Write predecessors generated by the CFG into
    /// the Block's preds list.
    ///
    /// We expect the block
    /// ids to remain stable across the CFG and
    /// initial lowering i.e. cfg.BlockId(1) == ir.BlockId(1)
    pub fn addPredecessors(b: *Block, p: *const Procedure, edges: []const cfg.Edge) !void {
        try b.preds.ensureUnusedCapacity(p.allocator, edges.len);
        // TODO: ir.BlockId and cfg.BlockIndex are the same thing - clean this up
        //   and remove the cast below
        for (edges) |edge| b.preds.appendAssumeCapacity(BlockId.from(edge.from));
    }

    fn terminator(b: *const Block, p: *const Procedure) ValueId {
        if (b.values.items.len == 0) return .none;
        const last = b.values.items[b.values.items.len - 1];
        return if (p.opcodeOf(last).isTerminator()) last else .none;
    }
};

/// like in B3! :)
pub const Procedure = struct {
    allocator: std.mem.Allocator,
    values: std.MultiArrayList(Value) = .empty,
    blocks: std.ArrayList(Block) = .empty,
    extra: std.ArrayList(u32) = .empty,

    pub fn deinit(p: *Procedure) void {
        p.values.deinit(p.allocator);
        p.extra.deinit(p.allocator);

        for (p.blocks.items) |*block| block.deinit(p.allocator);
        p.blocks.deinit(p.allocator);
    }

    inline fn opcodeOf(p: *const Procedure, vid: ValueId) OpCode {
        return p.values.items(.op)[vid.idx()];
    }

    inline fn reprOf(p: *const Procedure, vid: ValueId) Repr {
        return p.values.items(.repr)[vid.idx()];
    }

    inline fn effectsFor(p: *const Procedure, vid: ValueId) Effects {
        return effectsOf(p.opcodeOf(vid));
    }

    fn getValue(p: *const Procedure, vid: ValueId) Value {
        return p.values.get(vid.idx());
    }

    /// Extra Payloads - borrowing this DoD from Zig's own compiler
    fn addExtra(p: *Procedure, comptime T: type, payload: T) !u32 {
        const fields = std.meta.fields(T);
        // here we're assuming all fields are 32 bits
        try p.extra.ensureUnusedCapacity(p.allocator, fields.len);
        const off: u32 = @intCast(p.extra.items.len);
        inline for (fields) |f| {
            const raw: u32 = switch (@typeInfo(f.type)) {
                .@"enum" => @intFromEnum(@field(payload, f.name)),
                else => @field(payload, f.name),
            };
            p.extra.appendAssumeCapacity(raw);
        }
        return off;
    }

    /// fetch and decode "extra" payloads
    fn extraData(p: *const Procedure, comptime T: type, off: u32) T {
        var out: T = undefined;
        var i = off;
        inline for (std.meta.fields(T)) |f| {
            const raw = p.extra.items[i];
            @field(out, f.name) = switch (@typeInfo(f.type)) {
                .@"enum" => @enumFromInt(raw),
                else => @intCast(raw),
            };
            i += 1;
        }
        return out;
    }

    pub fn addBlock(p: *Procedure) !BlockId {
        const id = BlockId.from(@intCast(p.blocks.items.len));
        try p.blocks.append(p.allocator, .{});
        return id;
    }

    pub fn addValue(p: *Procedure, bid: BlockId, value: Value) !ValueId {
        const i = ValueId.from(@intCast(p.values.len));
        try p.values.append(p.allocator, value);
        var block = &p.blocks.items[bid.idx()];
        try block.values.append(p.allocator, i);
        return i;
    }

    pub fn addBranch(p: *Procedure, bid: BlockId, payload: BranchPayload) !ValueId {
        const extra_offset = try p.addExtra(BranchPayload.Extra, payload.extra);
        return try p.addValue(bid, .{
            .op = .branch,
            .repr = .i1,
            .lhs = payload.predicate,
            .rhs = extra_offset,
        });
    }

    pub fn successors(p: *const Procedure, bid: BlockId, buf: *[8]BlockId) []const BlockId {
        const term = p.blocks.items[bid.idx()].terminator(p);
        if (term == .none) return buf[0..0];
        const lhs = p.values.items(.lhs)[term.idx()];
        const rhs = p.values.items(.rhs)[term.idx()];
        switch (p.opcodeOf(term)) {
            .branch => {
                const extra = p.extraData(BranchPayload.Extra, rhs);
                buf[0] = extra.then;
                buf[1] = extra.@"else";
                return buf[0..2];
            },
            .jump => {
                buf[0] = @enumFromInt(lhs);
                return buf[0..1];
            },
            .ret => return buf[0..0],
            else => return buf[0..0],
        }
    }

    pub fn replaceWithIdentity(p: *Procedure, old: ValueId, new: ValueId) void {
        assert(old != new);
        assert(p.reprOf(old) == p.reprOf(new));
        p.values.items(.op)[old.idx()] = .identity;
        p.values.items(.lhs)[old.idx()] = @intFromEnum(new);
        p.values.items(.rhs)[old.idx()] = 0;
    }

    pub fn deleteValue(p: *Procedure, vid: ValueId) void {
        assert(!p.effectsFor(vid).terminator);
        p.values.items(.op)[vid.idx()] = .nop;
        p.values.items(.repr)[vid.idx()] = .none;
    }

    /// See through `identity` chains.  Every operand read should go thru this
    fn resolve(p: *const Procedure, vid: ValueId) ValueId {
        var cur = vid;
        const ops = p.values.items(.op);
        const lhs = p.values.items(.lhs);
        var guard: u32 = 0;
        while (cur != .none and ops[cur.idx()] == .identity) {
            cur = ValueId.from(lhs[cur.idx()]);
            guard += 1;
            assert(guard < 1_000_000); // we have an identity cycle bug
        }
        return cur;
    }
};

test {
    _ = lower;
}

test "procedure: encoding 'extra' data" {
    var proc: Procedure = .{
        .allocator = testing.allocator,
    };
    defer proc.deinit();

    const predicate: Value = .True;
    const root = try proc.addBlock();
    const then_b = try proc.addBlock();
    const else_b = try proc.addBlock();
    const predicate_id = try proc.addValue(root, predicate);
    const branch_extra: BranchPayload.Extra = .{ .then = then_b, .@"else" = else_b };

    try testing.expectEqual(0, proc.extra.items.len);

    const vid = try proc.addBranch(root, .{ .predicate = predicate_id.idx(), .extra = branch_extra });
    const branch_value = proc.getValue(vid);

    const payload = proc.extraData(BranchPayload.Extra, branch_value.rhs);
    try testing.expectEqual(branch_extra, payload);
}

test "procedure: block successors" {
    var proc: Procedure = .{
        .allocator = testing.allocator,
    };
    defer proc.deinit();

    const root = try proc.addBlock();
    const then_b = try proc.addBlock();
    const else_b = try proc.addBlock();

    const pred = try proc.addValue(root, .True);
    _ = try proc.addBranch(root, .{ .predicate = pred.idx(), .extra = .{ .then = then_b, .@"else" = else_b } });

    var buf: [8]BlockId = undefined;
    try testing.expectEqualSlices(BlockId, ([2]BlockId{ then_b, else_b })[0..], proc.successors(root, &buf));
}

test "procedure: resolve" {
    var proc: Procedure = .{
        .allocator = testing.allocator,
    };
    defer proc.deinit();

    const root = try proc.addBlock();
    const v1 = try proc.addValue(root, .True);
    const v2 = try proc.addValue(root, .True);
    proc.replaceWithIdentity(v2, v1);

    try testing.expectEqual(v1, proc.resolve(v2));
}
